[project]
name = "access-ci-account"
version = "0.1.0"
description = "ACCESS CI Django-CMS Test Front"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "Django>=5.2,<5.3",
    "django-cms>=5.0,<5.1",
    "requests>=2.32.0",
    "djangorestframework>=3.15.0",
    "gunicorn>=23.0,<24",
    "access-django-user-admin==1.4.6",
    "django-bootstrap5>=25.0,<26",
    "django-allauth>=65.0,<66",
    "psycopg2-binary>=2.9",
]

[tool.uv.sources]

[tool.uv.workspace]
members = ["packages/*"]